export class City {
	id: Number = 0;
	name: String = '';
	
	constructor(city) {
		if (city.id) {this.id = city.id}
		if (city.name) {this.name = city.name}
	}
}

export const CITIES = [
	new City({id: 0, name: 'Alice'}),
	new City({id: 1, name: 'Bellville'}),
	new City({id: 2, name: 'Benoni'}),
	new City({id: 3, name: 'Bethlehem'}),
	new City({id: 4, name: 'Bloemfontein'}),
	new City({id: 5, name: 'Boksburg'}),
	new City({id: 6, name: 'Brakpan'}),
	new City({id: 7, name: 'Butterworth'}),
	new City({id: 8, name: 'Cape Town'}),
	new City({id: 9, name: 'Carletonville'}),
	new City({id: 10, name: 'Constantia'}),
	new City({id: 11, name: 'Durban'}),
	new City({id: 12, name: 'East London'}),
	new City({id: 12, name: 'Emalahleni'}),
	new City({id: 14, name: 'Empangeni'}),
	new City({id: 15, name: 'George'}),
	new City({id: 16, name: 'Germiston'}),
	new City({id: 17, name: 'Giyani'}),
	new City({id: 18, name: 'Graaff-Reinet'}),
	new City({id: 19, name: 'Grahamstown'}),
	new City({id: 20, name: 'Hopefield'}),
	new City({id: 21, name: 'Jagersfontein'}),
	new City({id: 22, name: 'Johannesburg'}),
	new City({id: 23, name: 'Kimberley'}),
	new City({id: 24, name: 'King William’s Town'}),
	new City({id: 25, name: 'Klerksdorp'}),
	new City({id: 26, name: 'Kroonstad'}),
	new City({id: 27, name: 'Krugersdorp'}),
	new City({id: 28, name: 'Kuruman'}),
	new City({id: 29, name: 'Ladysmith'}),
	new City({id: 31, name: 'Lebowakgomo'}),
	new City({id: 32, name: 'Mahikeng'}),
	new City({id: 33, name: 'Mmabatho'}),
	new City({id: 34, name: 'Mthatha'}),
	new City({id: 35, name: 'Musina'}),
	new City({id: 36, name: 'Nelspruit'}),
	new City({id: 37, name: 'Newcastle'}),
	new City({id: 38, name: 'Odendaalsrus'}),
	new City({id: 39, name: 'Oudtshoorn'}),
	new City({id: 40, name: 'Paarl'}),
	new City({id: 41, name: 'Parys'}),
	new City({id: 42, name: 'Phalaborwa'}),
	new City({id: 43, name: 'Phuthaditjhaba'}),
	new City({id: 44, name: 'Pietermaritzburg'}),
	new City({id: 45, name: 'Pinetown'}),
	new City({id: 46, name: 'Polokwane'}),
	new City({id: 47, name: 'Port Elizabeth'}),
	new City({id: 48, name: 'Port Nolloth'}),
	new City({id: 49, name: 'Potchefstroom'}),
	new City({id: 51, name: 'Pretoria'}),
	new City({id: 52, name: 'Queenstown'}),
	new City({id: 53, name: 'Randburg'}),
	new City({id: 54, name: 'Randfontein'}),
	new City({id: 55, name: 'Roodepoort'}),
	new City({id: 56, name: 'Rustenburg'}),
	new City({id: 57, name: 'Sasolburg'}),
	new City({id: 58, name: 'Secunda'}),
	new City({id: 59, name: 'Seshego'}),
	new City({id: 60, name: 'Sibasa'}),
	new City({id: 70, name: 'Simon’s Town'}),
	new City({id: 71, name: 'Soweto'}),
	new City({id: 72, name: 'Springs'}),
	new City({id: 73, name: 'Stellenbosch'}),
	new City({id: 74, name: 'Swellendam'}),
	new City({id: 75, name: 'Thabazimbi'}),
	new City({id: 76, name: 'Uitenhage'}),
	new City({id: 77, name: 'Ulundi'}),
	new City({id: 78, name: 'Umlazi'}),
	new City({id: 79, name: 'Vanderbijlpark'}),
	new City({id: 80, name: 'Vereeniging'}),
	new City({id: 81, name: 'Virginia'}),
	new City({id: 82, name: 'Welkom'}),
	new City({id: 83, name: 'Worcester'}),
	new City({id: 84, name: 'Zwelitsha'}),
];